version: '3.8'

services:
  # MySQL 数据库服务
  mysql:
    image: mysql:8.0
    container_name: deer_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: deer_forum
      MYSQL_USER: deeruser
      MYSQL_PASSWORD: deer123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - deer_network

  # Node.js 后端服务
  backend:
    build: ./backend
    container_name: deer_backend
    restart: always
    environment:
      NODE_ENV: production
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: deer_forum
      DB_USER: deeruser
      DB_PASSWORD: deer123456
      JWT_SECRET: deer_jwt_secret_key_2024
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - deer_network
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Nginx 反向代理和 HTTPS 服务
  nginx:
    image: nginx:alpine
    container_name: deer_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
    networks:
      - deer_network

volumes:
  mysql_data:

networks:
  deer_network:
    driver: bridge
